Repository dariomtz/APIDOCS, pull requests merged in 2020-07, with the labels that each got.

#50 Adding footer
  functions/package-lock.json
  functions/package.json
  functions/views/layouts/main.html
  functions/views/user.html
  public/UserView.js
Labels: enhancement

#54 Delete endpoint feature
  functions/views/layouts/main.html
  functions/views/project.html
  public/EndpointView.js
Labels: enhancement

#58 Link to author feature
  functions/views/project.html
Labels: UX, enhancement

#59 Edit resource form fix
  public/ResourceController.js
  public/ResourceView.js
Labels: UX

#60 Landing page
  functions/views/layouts/main.html
  functions/views/welcome.html
  public/UsernameIcon.svg
  public/landingPageImg.svg
Labels: UX, enhancement
